name: Server Build & Push

env:
  IMAGE_NAME: ep-mern-authservice
  BRANCH_NAME: ${{ github.ref}}
  BUILD_TAG: ${{ github.sha }}

on:
  push:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      # # - name: echo docker-compose
      # #   run: cat docker-compose.yaml

      - name: Login to Docker Repository
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # # - name: Create env file
      # #   run: |
      # #     touch .env 
      # #     echo "${{ secrets.SERVER_ENV_PROD }}" > .env
      # #     echo "BUILD_TAG=${{ env.BUILD_TAG }}" > .env
      # #     cat .env

      - name: Build image
        run: docker compose -f docker-compose.yml build

      # - name: Set KUBECONFIG environment variable
      #   run: |
      #     echo "$KUBECONFIG_CONTENT" > config.yml
      #     export KUBECONFIG=$(pwd)/config.yml

      # # - name: echo env
      # #   run: echo ${{ env.BUILD_TAG }}

      # # - name: test images
      # #   run: | 
      # #     docker images

      # # - name: test
      #   # run: source environment.sh envsubst < aks-config.yaml.template > aks-config.yaml |
      #     # cat aks-config.yaml

      - name: Push Docker image to Azure Container Registry
        run: |
          docker tag ${{ env.IMAGE_NAME }}:latest ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}:${{ env.BUILD_TAG }}
          docker push ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}:${{ env.BUILD_TAG }}

      - name: Apply Kubernetes manifest file
        run: |
          export BUILD_TAG=${{ env.BUILD_TAG }}
          export PORT=${{env.PORT}}
          envsubst < manifests/templates/aks-config.yml | kubectl apply -f - -n ep-mern --kubeconfig=config.yml
          envsubst < manifests/templates/config-map.yml | kubectl apply -f - -n ep-mern --kubeconfig=config.yml

      - name: Apply Kubernetes ingress file
        run: |
          envsubst < manifests/templates/ingress-conf.yml | kubectl apply -f - -n ep-mern --kubeconfig=config.yml